/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardButton: typeof import('./src/components/BoardButton.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    FooterLine: typeof import('./src/components/FooterLine.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    GameboardTopRightButtons: typeof import('./src/components/GameboardTopRightButtons.vue')['default']
    GameOptionsPanel: typeof import('./src/components/GameOptionsPanel.vue')['default']
    GameplayBoard: typeof import('./src/components/GameplayBoard.vue')['default']
    HelpButton: typeof import('./src/components/HelpButton.vue')['default']
    IMdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    IMdiVolumeHigh: typeof import('~icons/mdi/volume-high')['default']
    IMdiVolumeOff: typeof import('~icons/mdi/volume-off')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    RoundLine: typeof import('./src/components/RoundLine.vue')['default']
    SolutionPanel: typeof import('./src/components/SolutionPanel.vue')['default']
    SoundButton: typeof import('./src/components/SoundButton.vue')['default']
    StatsDisplay: typeof import('./src/components/StatsDisplay.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
